# Generated by Django 2.0.3 on 2018-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180315_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updating',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'YES')], default=0),
        ),
    ]
